language: node_js
sudo: false
node_js:
  - node
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
matrix:
fast_finish: true
before_script:
  - npm i -g typescript rimraf
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
