language: node_js
sudo: false
node_js:
  - node
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
matrix:
before_script:
  - npm i -g typescript rimraf
after_success:
  - npm run coverage
  - npm run report-coverage
